/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Item = IDL.Record({
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'name' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'items' : IDL.Vec(Item),
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Item), IDL.Nat],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Item = IDL.Record({
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'name' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'items' : IDL.Vec(Item),
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Item), IDL.Nat],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };